name: 'Auto Assign PR'

on:
  workflow_run:
    workflows: ["Pull Request Opened"]
    types:
      - completed

jobs:
    log-info:
        name: "Add reviewers to PR"
        runs-on: ubuntu-latest
        steps:
          - name: "echo variables"
            run: |
              echo \"${{ github.event.workflow_run.event }}\"
              echo \"${{ github.event.pull_request.types }}\"
              echo \"${{ github.actor }}\"

    add-reviewers:
        name: "Add reviewers to PR"
        if: >
          github.event.workflow_run.event == 'pull_request' &&
          github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
          GIT_AUTHOR_NAME: mparticle-automation
          GIT_AUTHOR_EMAIL: developers@mparticle.com
          GIT_COMMITTER_NAME: mparticle-automation
          GIT_COMMITTER_EMAIL: developers@mparticle.com
        runs-on: ubuntu-latest
        steps:
          - name: 'Print Event'
            run: |
              echo ${{ github.event.workflow_run.event }}
          - name: 'Download artifact'
            uses: actions/github-script@v3.1.0
            with:
              script: |
                var artifacts = await github.actions.listWorkflowRunArtifacts({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   run_id: ${{ github.event.workflow_run.id }},
                });
                var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
                  return artifact.name == "pr"
                })[0];
                var download = await github.actions.downloadArtifact({
                   owner: context.repo.owner,
                   repo: context.repo.repo,
                   artifact_id: matchArtifact.id,
                   archive_format: 'zip',
                });
                var fs = require('fs');
                fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
          - run: unzip pr.zip
          - name: 'Automerge PR'
            id: find-pr
            uses: actions/github-script@v3
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                var fs = require('fs');
                var titleString = String(fs.readFileSync('./NR'));
#                echo "::set-output name=title::titleString"
                echo "::set-output name=title::$titleString"
          - name: "echo variables"
            run: |
              echo \"${{ steps.find-pr.outputs.title }}\"

          - name: "Check PR title"
            id: is-docs
            if: >
                startsWith(${{ steps.find-pr.outputs.title }}, 'docs:')
            run: |
                OUTPUT=true
                echo "::set-output name=isDocs::$OUTPUT"
          - name: "echo isDocs"
            run: |
                echo ${{ steps.is-docs.outputs.isDocs }}
          - name: "PR title is docs"
            if: ${{steps.is-docs.outputs.isDocs == 'true'}}
            uses: pozil/auto-assign-issue@v1
            with:
                teams: docs-triage
                numOfAssignee: 1
                allowSelfAssign: false
                repo-token: ${{ secrets.MP_SEMANTIC_RELEASE_BOT}}
          - name: "PR title is not docs"
            if: ${{ steps.is-docs.outputs.isDocs != 'true'}}
            uses: pozil/auto-assign-issue@v1
            with:
                teams: android-triage
                numOfAssignee: 1
                allowSelfAssign: false
                repo-token: ${{ secrets.MP_SEMANTIC_RELEASE_BOT}}
