name: Create Jira Issue

on:
  issues:
    types: ["opened", "reopened"]

jobs:
  create-issue:
    name: "Create Issue"
    uses: mParticle/mparticle-workflows/.github/workflows/issue-to-jira-ticket.yml@main
    secrets: inherit
